# Generated by Django 5.2.8 on 2025-11-15 17:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier', primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, help_text='6-digit verification code', max_length=6)),
                ('mobile_number', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')])),
                ('expires_at', models.DateTimeField(editable=False, help_text='Timestamp after which the code becomes invalid')),
                ('is_used', models.BooleanField(default=False, help_text='Tracks whether the OTP has already been used')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the OTP was generated')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier', primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, help_text='Email or phone number being targeted', max_length=255)),
                ('attempt_type', models.CharField(choices=[('generation', 'Generation'), ('verification', 'Verification'), ('resend', 'Resend')], help_text='Type of OTP attempt', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the requester')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the attempt was made')),
                ('success', models.BooleanField(default=False, help_text='Whether the attempt was successful')),
                ('error_message', models.CharField(blank=True, help_text='Error message if attempt failed', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the attempt')),
                ('otp', models.ForeignKey(blank=True, help_text='Related OTP record (for verification attempts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='OTP.otp')),
            ],
            options={
                'verbose_name': 'OTP Attempt',
                'verbose_name_plural': 'OTP Attempts',
                'db_table': 'otp_attempt',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['identifier', 'attempt_type', 'timestamp'], name='idx_identifier_type_time'), models.Index(fields=['ip_address', 'timestamp'], name='idx_ip_time'), models.Index(fields=['otp', 'success', 'timestamp'], name='idx_otp_success_time'), models.Index(fields=['timestamp'], name='idx_timestamp')],
            },
        ),
    ]
