# Generated by Django 5.2.4 on 2025-11-14 03:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.BooleanField(default=True, help_text='Indicates whether the company is active or not.')),
            ],
        ),
        migrations.CreateModel(
            name='SchemeFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('file_choice', models.CharField(choices=[('successful_applicants', 'successful_applicants'), ('Rejected_applicants', 'Rejected_applicants'), ('lottery_winners', 'lottery_winners'), ('news_papaer_cut', 'news_papaer_cut'), ('other', 'other')], default='other', max_length=100)),
                ('file', models.FileField(upload_to='myfiles/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scheme.scheme')),
            ],
        ),
    ]
