# Generated by Django 5.2.4 on 2025-11-14 05:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemefiles',
            old_name='parent',
            new_name='Scheme',
        ),
        migrations.AddField(
            model_name='scheme',
            name='appeal_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='application_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='application_open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='lottery_result_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='successful_applicants_publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'coming_soon'), ('application_open', 'application_open'), ('applications_under_review', 'applications_under_review'), ('appeal_period', 'appeal_period'), ('lottery_anounced', 'lottery_anounced'), ('other', 'other')], default='coming_soon', max_length=100),
        ),
    ]
