# Generated by Django 5.2.4 on 2025-11-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0002_rename_parent_schemefiles_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='company',
            field=models.CharField(choices=[('riyasat infra', 'riyasat infra'), ('riyasal llp', 'riyasal llp'), ('new infra', 'new infra'), ('other', 'other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='status',
            field=models.CharField(choices=[('coming_soon', 'coming_soon'), ('application_open', 'application_open'), ('applications_under_review', 'applications_under_review'), ('appeal_period', 'appeal_period'), ('lottery_yet_to_anounce', 'lottery_yet_to_anounce'), ('lottery_anounced', 'lottery_anounced'), ('closed', 'closed')], default='coming_soon', max_length=100),
        ),
    ]
