# Generated by Django 5.2.4 on 2025-11-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0003_scheme_company_alter_scheme_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='status',
        ),
    ]
