# Generated by Django 5.2.4 on 2025-11-14 08:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0004_remove_scheme_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='Lig_plot_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='application_number_start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='ews_plot_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='reserved_rate',
            field=models.IntegerField(default=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schemefiles',
            name='file_choice',
            field=models.CharField(choices=[('terms and condations', 'terms and condations'), ('scheme details', 'scheme details'), ('successful_applicants', 'successful_applicants'), ('Rejected_applicants', 'Rejected_applicants'), ('lottery_winners', 'lottery_winners'), ('news_papaer_cut', 'news_papaer_cut'), ('other', 'other')], default='other', max_length=100),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')])),
                ('applicant_name', models.CharField(max_length=200)),
                ('father_husband_name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('id_type', models.CharField(choices=[('AADHAR', 'Aadhar Card'), ('RATION_CARD', 'Ration Card'), ('JAN_AADHAR', 'Jan Aadhar Card'), ('VOTER_ID', 'Voter ID Card'), ('DRIVING_LICENSE', 'Driving License')], max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number (e.g., ABCDE1234F)', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')])),
                ('permanent_address', models.TextField()),
                ('permanent_address_pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit pincode', regex='^\\d{6}$')])),
                ('postal_address', models.TextField()),
                ('postal_address_pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit pincode', regex='^\\d{6}$')])),
                ('email', models.EmailField(max_length=254)),
                ('annual_income', models.CharField(choices=[('UP_TO_3L', 'Up to 3 Lakhs'), ('3L_6L', '3 Lakhs to 6 Lakhs')], max_length=20)),
                ('plot_category', models.CharField(choices=[('EWS', 'Economically Weaker Section'), ('LIG', 'Low Income Group')], editable=False, max_length=10)),
                ('registration_fees', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('processing_fees', models.DecimalField(decimal_places=2, default=500.0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_payable_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_mode', models.CharField(choices=[('DD', 'Demand Draft'), ('UPI', 'UPI')], max_length=10)),
                ('dd_id_or_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='DD ID/Transaction ID')),
                ('dd_date_or_transaction_date', models.DateField(blank=True, null=True, verbose_name='DD Date/Transaction Date')),
                ('dd_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='DD Amount/Transaction Amount')),
                ('payee_account_holder_name', models.CharField(blank=True, max_length=200)),
                ('payee_bank_name', models.CharField(blank=True, max_length=200)),
                ('transaction_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Transaction Screenshot / DD Photo')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('refund_account_holder_name', models.CharField(blank=True, max_length=200)),
                ('refund_account_number', models.CharField(blank=True, max_length=20)),
                ('refund_bank_name', models.CharField(blank=True, max_length=200)),
                ('refund_bank_branch_address', models.TextField()),
                ('refund_bank_ifsc', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('application_submission_date', models.DateTimeField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_remark', models.TextField(blank=True)),
                ('lottery_status', models.CharField(choices=[('NOT_CONDUCTED', 'Not Conducted'), ('SELECTED', 'Selected'), ('NOT_SELECTED', 'Not Selected'), ('WAITLISTED', 'Waitlisted')], default='NOT_CONDUCTED', max_length=20)),
                ('application_pdf', models.FileField(blank=True, null=True, upload_to='application_pdfs/', verbose_name='Application PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='scheme.scheme')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-application_submission_date'],
                'unique_together': {('scheme', 'mobile_number')},
            },
        ),
    ]
