# Generated by Django 5.2.4 on 2025-11-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0005_scheme_lig_plot_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='father_husband_name',
            new_name='father_or_husband_name',
        ),
    ]
