# Generated by Django 5.2.4 on 2025-11-14 09:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0006_rename_father_husband_name_application_father_or_husband_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='dd_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='DD Amount/Transaction Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='dd_date_or_transaction_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DD Date/Transaction Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='dd_id_or_transaction_id',
            field=models.CharField(default=123, max_length=100, verbose_name='DD ID/Transaction ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='payee_account_holder_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='payee_bank_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='refund_account_holder_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='refund_account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='refund_bank_ifsc',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='refund_bank_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='transaction_screenshot',
            field=models.ImageField(default=134, upload_to='payment_proofs/', verbose_name='Transaction Screenshot / DD Photo'),
            preserve_default=False,
        ),
    ]
