# Generated by Django 5.2.4 on 2025-11-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0007_alter_application_dd_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='application_number_start',
        ),
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.IntegerField(blank=True, db_index=True, default=1, editable=False, help_text='Auto-generated sequential number unique to every application', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='next_application_number',
            field=models.IntegerField(default=1, editable=False, help_text='set it to the number from where you want to start application number for the given scheme'),
            preserve_default=False,
        ),
    ]
