# Generated by Django 5.2.4 on 2025-11-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0008_remove_scheme_application_number_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='application_number_start',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
