# Generated by Django 5.2.4 on 2025-11-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0009_scheme_application_number_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='transaction_screenshot',
            new_name='payment_proof',
        ),
    ]
