# Generated by Django 5.2.8 on 2025-11-15 16:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0010_rename_transaction_screenshot_application_payment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID identifier', primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, help_text='6-digit verification code', max_length=6)),
                ('expires_at', models.DateTimeField(editable=False, help_text='Timestamp after which the code becomes invalid')),
                ('is_used', models.BooleanField(default=False, help_text='Tracks whether the OTP has already been used')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the OTP was generated')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
