# Generated by Django 5.2.8 on 2025-11-15 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0011_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='mobile_number',
            field=models.CharField(default=9987654321, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
