# Generated by Django 5.2.8 on 2025-11-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0012_otp_mobile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
