# Generated by Django 5.2.8 on 2025-11-16 16:13

import scheme.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0013_delete_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='payment_proof',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=scheme.models.Application.payment_proof_upload_path, verbose_name='Transaction Screenshot / DD Photo'),
        ),
    ]
