# Generated by Django 5.2.8 on 2025-11-19 10:39

import django.core.validators
import scheme.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0014_alter_application_payment_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemefiles',
            old_name='Scheme',
            new_name='scheme',
        ),
        migrations.AlterField(
            model_name='schemefiles',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=scheme.models.SchemeFiles.file_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])]),
        ),
    ]
