# Generated by Django 5.2.8 on 2025-11-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0015_rename_scheme_schemefiles_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemefiles',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schemefiles',
            unique_together={('scheme', 'name')},
        ),
    ]
