# Generated by Django 5.2.8 on 2025-11-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0016_alter_schemefiles_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='reserved_rate',
        ),
        migrations.AddField(
            model_name='scheme',
            name='reserved_price',
            field=models.IntegerField(default=5000, verbose_name='Reserved Price per Sq Meter'),
            preserve_default=False,
        ),
    ]
