# Generated by Django 5.2.8 on 2025-11-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0017_remove_scheme_reserved_rate_scheme_reserved_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_type',
            field=models.CharField(choices=[('PAN_CARD', 'Pan Card'), ('RATION_CARD', 'Ration Card'), ('JAN_AADHAR', 'Jan Aadhar Card'), ('VOTER_ID', 'Voter ID Card'), ('DRIVING_LICENSE', 'Driving License')], max_length=20),
        ),
    ]
