# Generated by Django 5.2.8 on 2025-11-22 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0018_alter_application_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='application',
            name='aadhar_number',
            field=models.CharField(default=123456789012, max_length=12, validators=[django.core.validators.RegexValidator(message='Enter a valid Aadhar number (12 digits)', regex='^[0-9]{12}$')]),
            preserve_default=False,
        ),
    ]
