# Generated by Django 5.2.8 on 2025-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0019_remove_application_pan_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='dd_amount',
            new_name='dd_amount_or_transaction_amount',
        ),
        migrations.AddField(
            model_name='application',
            name='sub_category',
            field=models.CharField(choices=[('EWS_GENERAL', 'EWS - General'), ('EWS_SC', 'EWS - SC'), ('EWS_ST', 'EWS - ST'), ('EWS_OBC', 'EWS - OBC'), ('LIG_GENERAL', 'LIG - General'), ('LIG_SC', 'LIG - SC'), ('LIG_ST', 'LIG - ST'), ('LIG_OBC', 'LIG - OBC')], default='EWS_GENERAL', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='plot_category',
            field=models.CharField(choices=[('EWS', 'Economically Weaker Section'), ('LIG', 'Low Income Group')], max_length=10),
        ),
    ]
