# Generated by Django 5.2.8 on 2025-11-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0020_rename_dd_amount_application_dd_amount_or_transaction_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='payee_account_holder_name',
            new_name='payer_account_holder_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='payee_bank_name',
            new_name='payer_bank_name',
        ),
    ]
