# Generated by Django 5.2.8 on 2025-11-22 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0021_rename_payee_account_holder_name_application_payer_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='refund_account_holder_name',
            new_name='applicant_account_holder_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='refund_account_number',
            new_name='applicant_account_number',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='refund_bank_branch_address',
            new_name='applicant_bank_branch_address',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='refund_bank_ifsc',
            new_name='applicant_bank_ifsc',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='refund_bank_name',
            new_name='applicant_bank_name',
        ),
    ]
