# Generated by Django 5.2.8 on 2025-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0022_rename_refund_account_holder_name_application_applicant_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.IntegerField(blank=True, db_index=True, editable=False, help_text='Auto-generated sequential number unique to every application'),
        ),
    ]
