# Generated by Django 5.2.8 on 2025-11-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0023_alter_application_application_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('scheme', 'application_number'), ('scheme', 'mobile_number')},
        ),
    ]
