# Generated by Django 5.2.8 on 2025-11-24 15:53

import scheme.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0023_alter_application_application_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('scheme', 'application_number'), ('scheme', 'mobile_number')},
        ),
        migrations.AlterField(
            model_name='application',
            name='application_pdf',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=scheme.models.Application.application_pdf_upload_path, verbose_name='Application PDF'),
        ),
    ]
