# Generated by Django 5.2.8 on 2025-11-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheme', '0025_alter_application_application_pdf'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('scheme', 'aadhar_number'), ('scheme', 'applicant_account_number'), ('scheme', 'application_number'), ('scheme', 'mobile_number')},
        ),
        migrations.AlterField(
            model_name='application',
            name='annual_income',
            field=models.CharField(choices=[('0L_3L', '0 to 3 Lakhs'), ('3L_6L', '3 Lakhs to 6 Lakhs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_type',
            field=models.CharField(choices=[('PAN_CARD', 'Pan Card'), ('VOTER_ID', 'Voter ID Card'), ('DRIVING_LICENSE', 'Driving License'), ('RATION_CARD', 'Ration Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='sub_category',
            field=models.CharField(choices=[('un-reserved', 'Un-Reserved'), ('un-reserved-dls', 'Un-Reserved (Destitute & Landless Single)'), ('un-reserved-handicap', 'Un-Reserved Handicap'), ('gov-employees', 'Government Employees'), ('journalist', 'Journalist'), ('other-soldiers', 'Other soldiers (including ex-servicemen)'), ('sc', 'Scheduled Caste'), ('st', 'Scheduled Tribe'), ('soldier-handicapped', 'Soldier Handicapped'), ('soldier-widow-dependent', 'Soldier (Widow & Dependent)'), ('transgender', 'Transgender')], max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='company',
            field=models.CharField(choices=[('riyasat-infra', 'Riyasat Infra Developers Pvt. Ltd.'), ('riyasat-infratech', 'Riyasat Infratech Developers LLP'), ('new-path', 'New Path Developers LLP'), ('gokul-kripa', 'Gokul Kripa Colonizers and Developers Pvt. Ltd.'), ('other', 'other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='schemefiles',
            name='file_choice',
            field=models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('scheme_details', 'Scheme Details'), ('successful_applicants', 'Successful Applicants'), ('rejected_applicants', 'Rejected Applicants'), ('lottery_winners', 'Lottery Winners'), ('newspaper_cut', 'Newspaper Cuttings'), ('payment_qr_code', 'Payment QR Code'), ('other', 'Other')], max_length=100),
        ),
    ]
